name: My First CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      MY_NAME: Teddy

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello $MY_NAME!"


      - name: Check if HTML file exists
        run: test -f index.html
        
      - name: Use secret
        run: echo "I love my ${{ secrets.SECRET_TOY }}"

